# Generated by Django 4.2 on 2023-04-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="platforms",
        ),
        migrations.AddField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(to="games.platform"),
        ),
    ]
